apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto-broker
  template:
    metadata:
      labels:
        app: mosquitto-broker
    spec:
      containers:
      - name: mosquitto-broker
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: config-volume
          mountPath: /mosquitto/config
      volumes:
        - name: config-volume
          configMap:
           name: mosquitto-config
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-broker-service
spec:
  selector:
    app: mosquitto-broker
  ports:
  - protocol: TCP
    port: 1883
    targetPort: 1883
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    persistence false
    max_inflight_messages 65530
    max_packet_size 1000000
    max_queued_messages 100000
    connection_messages true
    log_type all
