apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  labels:
    app: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image: docker.io/alialemana/subscriber:v0.0.3
        imagePullPolicy: Always
        env:
        - name: BROKER
          value: mosquitto-broker-service
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sub-secret
              key: password
